export const GET_NOTES = "GET_NOTES"
export const CREATE_NOTE = "CREATE_NOTE"
export const DELETE_NOTE = "DELETE_NOTE"
export const EDIT_NOTE = "EDIT_NOTE"



export const GET_CATEGORIES = "GET_CATEGORIES"
export const CREATE_CATEGORY = "CREATE_CATEGORY"
export const DELETE_CATEGORY = "DELETE_CATEGORY"


export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY"
export const FILTER_BY_ARCHIVED = "FILTER_BY_ARCHIVED"
export const CLEAR_FILTERED = "CLEAR_FILTERED"
export const SET_ARCHIVED_VALUE = "SET_ARCHIVED_VALUE"
export const SET_CATEGORY_VALUE = "SET_CATEGORY_VALUE"
export const ORDER_BY_ID = "ORDER_BY_ID"

